# Generated by Django 3.1.7 on 2021-03-07 23:35

import core.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210307_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=stdimage.models.StdImageField(upload_to=core.models.get_file_path, verbose_name='Imagem'),
        ),
    ]
